wtf:
  grid:
    columns: [54, 54, 54, 54, 54, 54, 54]
    rows: [12, 12, 12, 12, 12, 12]
  refreshInterval: 1
  term: 'xterm-kitty'
  mods:
    github:
      # Set environment variable WTF_GITHUB_TOKEN
      # From https://github.com/settings/tokens
      enabled: true
      position:
        top: 0
        left: 0
        height: 2
        width: 1
      refreshInterval: 300
      customQueries:
        othersPRs:
          title: 'Others Pull Requests'
          filter: 'is:open is:pr -author:doctorfree'
        bugs:
          title: 'Bugs'
          filter: 'is:issue is:open label:bug'
        issues:
          title: 'Issues'
          filter: 'is:issue is:open'
      username: doctorfree
      repositories:
        - 'doctorfree/MusicPlayerPlus'
        - 'doctorfree/Asciiville'
        - 'doctorfree/DoctorFreeScripts'
    security:
      enabled: true
      position:
        top: 0
        left: 3
        height: 1
        width: 1
      refreshInterval: 3600
    clocks:
      enabled: true
      position:
        top: 1
        left: 3
        height: 1
        width: 1
      colors:
        rows:
          even: 'lightblue'
          odd: 'white'
      locations:
        # From https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        Santa Cruz: 'America/Los_Angeles'
        Enid: 'America/Chicago'
        London: 'Europe/London'
        Singapore: 'Asia/Singapore'
        Peru: 'America/Lima'
        New Zealand: 'Pacific/Auckland'
        New York: 'America/New_York'
        UTC: 'Etc/UTC'
      refreshInterval: 15
      sort: 'chronological'
    ipapi:
      colors:
        name: red
        value: white
      # Optional  
      args:
        - "ip"
        - "isp"
        - "as"
        - "city"
        - "regionName"
        - "country"
        - "continent"
        - "coordinates"
        - "organization"
        - "timezone"
        - "reverseDNS"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 150s
    ipinfo:
      position:
        top: 1
        left: 2
        height: 1
        width: 1
      colors:
        name: red
        value: white
      enabled: true
      refreshInterval: 150
    weather:
      # Set environment variable WTF_OWM_API_KEY
      # From https://home.openweathermap.org
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      cityids:
        - 5393052
        - 6173331
        - 3128760
        - 6167865
        - 6176823
      colors:
        current: 'lightblue'
      enabled: true
      language: 'EN'
      refreshInterval: 900
      tempUnit: 'F'
      useEmoji: true
    prettyweather:
      enabled: true
      city: "Santa Cruz, California"
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 5m
      unit: "u"
      view: 0
      language: "en"
    prices_cryptolive:
      enabled: true
      position:
        top: 2
        left: 0
        height: 2
        width: 1
      updateInterval: 15
      currencies:
        ADA:
          displayName: Cardano
          to:
            - USD
        RNDR:
          displayName: Render Token
          to:
            - USD
        AGI:
          displayName: SingularityNET
          to:
            - USD
        COTI:
          displayName: COTI
          to:
            - USD
        GRT:
          displayName: The Graph
          to:
            - USD
        HNT:
          displayName: Helium
          to:
            - USD
      top:
        ADA:
          displayName: Cardano
          limit: 1
          to:
            - USD
      colors:
        from:
          name: coral
          displayName: grey
        to:
          name: white
          price: green
        top:
          from:
            name: grey
            displayName: coral
          to:
            name: red
            field: white
            value: green
      type: cryptolive
    ada_cryptolive:
      enabled: true
      position:
        top: 2
        left: 1
        height: 2
        width: 1
      updateInterval: 15
      currencies:
        ADA:
          displayName: Cardano
          to:
            - USD
      top:
        ADA:
          displayName: Cardano
          limit: 5
          to:
            - USD
      colors:
        from:
          name: coral
          displayName: grey
        to:
          name: white
          price: green
        top:
          from:
            name: grey
            displayName: coral
          to:
            name: red
            field: white
            value: green
      type: cryptolive
    rndr_cryptolive:
      enabled: true
      position:
        top: 2
        left: 2
        height: 2
        width: 1
      updateInterval: 15
      currencies:
        RNDR:
          displayName: Render Token
          to:
            - USD
      top:
        RNDR:
          displayName: Render Token
          limit: 5
          to:
            - USD
      colors:
        from:
          name: coral
          displayName: grey
        to:
          name: white
          price: green
        top:
          from:
            name: grey
            displayName: coral
          to:
            name: red
            field: white
            value: green
      type: cryptolive
    agix_cryptolive:
      enabled: true
      position:
        top: 2
        left: 3
        height: 2
        width: 1
      updateInterval: 15
      currencies:
        AGI:
          displayName: SingularityNET
          to:
            - USD
      top:
        AGI:
          displayName: SingularityNET
          limit: 5
          to:
            - USD
      colors:
        from:
          name: coral
          displayName: grey
        to:
          name: white
          price: green
        top:
          from:
            name: grey
            displayName: coral
          to:
            name: red
            field: white
            value: green
      type: cryptolive
    coti_cryptolive:
      enabled: true
      position:
        top: 2
        left: 4
        height: 2
        width: 1
      updateInterval: 15
      currencies:
        COTI:
          displayName: COTI
          to:
            - USD
      top:
        COTI:
          displayName: COTI
          limit: 5
          to:
            - USD
      colors:
        from:
          name: coral
          displayName: grey
        to:
          name: white
          price: green
        top:
          from:
            name: grey
            displayName: coral
          to:
            name: red
            field: white
            value: green
      type: cryptolive
    grt_cryptolive:
      enabled: true
      position:
        top: 2
        left: 5
        height: 2
        width: 1
      updateInterval: 15
      currencies:
        GRT:
          displayName: The Graph
          to:
            - USD
      top:
        GRT:
          displayName: The Graph
          limit: 5
          to:
            - USD
      colors:
        from:
          name: coral
          displayName: grey
        to:
          name: white
          price: green
        top:
          from:
            name: grey
            displayName: coral
          to:
            name: red
            field: white
            value: green
      type: cryptolive
    hnt_cryptolive:
      enabled: true
      position:
        top: 2
        left: 6
        height: 2
        width: 1
      updateInterval: 15
      currencies:
        HNT:
          displayName: Helium
          to:
            - USD
      top:
        HNT:
          displayName: Helium
          limit: 5
          to:
            - USD
      colors:
        from:
          name: coral
          displayName: grey
        to:
          name: white
          price: green
        top:
          from:
            name: grey
            displayName: coral
          to:
            name: red
            field: white
            value: green
      type: cryptolive
