wtf:
  grid:
    columns: [54, 54, 54, 54, 54]
    rows: [18, 18, 18, 18]
  refreshInterval: 1
  term: 'xterm-kitty'
  mods:
    github:
      # Set environment variable WTF_GITHUB_TOKEN
      # From https://github.com/settings/tokens
      enabled: true
      position:
        top: 0
        left: 0
        height: 2
        width: 1
      refreshInterval: 300
      customQueries:
        othersPRs:
          title: 'Others Pull Requests'
          filter: 'is:open is:pr -author:doctorfree'
        bugs:
          title: 'Bugs'
          filter: 'is:issue is:open label:bug'
        issues:
          title: 'Issues'
          filter: 'is:issue is:open'
      username: doctorfree
      repositories:
        - 'doctorfree/MusicPlayerPlus'
        - 'doctorfree/Asciiville'
        - 'doctorfree/DoctorFreeScripts'
    security:
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 3600
    clocks:
      enabled: true
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      colors:
        rows:
          even: 'lightblue'
          odd: 'white'
      locations:
        # From https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        SanFrancisco: 'America/Los_Angeles'
        Singapore: 'Asia/Singapore'
        Peru: 'America/Lima'
        NewZealand: 'Pacific/Auckland'
        NewYork: 'America/New_York'
        UTC: 'Etc/UTC'
      refreshInterval: 15
      sort: 'chronological'
    ipinfo:
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      colors:
        name: red
        value: white
      enabled: true
      refreshInterval: 150
    prettyweather:
      enabled: true
      city: "Santa Cruz, California"
      position:
        top: 1
        left: 2
        height: 1
        width: 1
      refreshInterval: 5m
      unit: "u"
      view: 0
      language: "en"
    weather:
      # Set environment variable WTF_OWM_API_KEY
      # From https://home.openweathermap.org
      position:
        top: 1
        left: 2
        height: 1
        width: 1
      cityids:
        - 5393052
        - 6173331
        - 3128760
        - 6167865
        - 6176823
      colors:
        current: 'lightblue'
      enabled: false
      language: 'EN'
      refreshInterval: 900
      tempUnit: 'F'
      useEmoji: true
